### create
POST http://localhost:8080/api/data
Content-Type: application/json

{ "name": "first"}

### query 1
GET http://localhost:8080/api/data/1

### update 1
PUT http://localhost:8080/api/data/1
Content-Type: application/json

{ "name": "update first"}

### delete 1
DELETE  http://localhost:8080/api/data/1

### list all
GET http://localhost:8080/api/data
