spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/h2;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: h2
